---
vaultwarden_container_name: vaultwarden
vaultwarden_network_name: vaultwarden_network
vaultwarden_subdomain: vault
vaultwarden_dashboard_url: https://{{ vaultwarden_subdomain }}.{{ site_url }}
vaultwarden_dashboard_name: Vaultwarden
vaultwarden_homer:
  name: "{{ vaultwarden_dashboard_name }}"
  category: services
vaultwarden_log_file: "{{ docker_dir }}/{{ vaultwarden_container_name }}/vaultwarden.log"
