---
# Paths to executables
snapraid_btrfs_executable: /usr/local/bin/snapraid-btrfs
snapraid_executable: /usr/local/bin/snapraid

# SnapRAID configuration path
snapraid_config: /etc/snapraid.conf

# Logging
snapraid_logging_file: /var/local/log/snapraid-btrfs-runner.log
snapraid_logging_maxsize: 5000

# SnapRAID settings
snapraid_touch: false
snapraid_deletethreshold: 15000

# snapraid-btrfs-runner settings
snapraid_btrfs_runner_dir: /usr/local/share/snapraid-btrfs-runner
snapraid_btrfs_pool: false
snapraid_btrfs_cleanup: true

# Scrub settings
snapraid_scrub_enabled: false
snapraid_scrub_plan: 12
snapraid_scrub_older_than: 10
