---
# The debian/ubuntu provided LCDd package doesn't include the lis driver
# which is required for the "nmedia PRO-LCD". For this reason I manually
# compile it.
- name: Install required system packages
  ansible.builtin.package:
    name:
      - autoconf
      - automake
      - build-essential
      - git
      - libftdi-dev
      - libusb-dev
      - pkg-config
    state: latest

- name: Clone LCDproc repository
  ansible.builtin.git:
    repo: "https://github.com/lcdproc/lcdproc.git"
    dest: "{{ lcdproc_repo_path }}"
    version: "master"
  register: lcdproc_git_clone

- name: Run autogen.sh
  ansible.builtin.command:
    cmd:
    chdir: "{{ lcdproc_repo_path }}"
  when: lcdproc_git_clone.changed

- name: Configure the build
  ansible.builtin.command:
    cmd: ./configure --enable-drivers=lis
    chdir: "{{ lcdproc_repo_path }}"
  when: lcdproc_git_clone.changed

- name: Build the program
  community.general.make:
    chdir: "{{ lcdproc_repo_path }}"
    target: all

- name: Install the program
  community.general.make:
    chdir: "{{ lcdproc_repo_path }}"
    target: install

- name: Fix configuration
  ansible.builtin.lineinfile:
    path: "{{ lcdproc_conf_dir }}/LCDd.conf"
    regexp: "^{{ item[0] }}"
    line: "{{ item[0] }}{{ item[1] }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - ["DriverPath=", "{{ lcdproc_prefix }}/lib/lcdproc/"]
    - ["Driver=", "lis"]

- name: Copy and configure LCDd server file
  ansible.builtin.template:
    src: lcdproc.service.j2
    dest: /etc/systemd/system/lcdproc.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart LCDd service

- name: Ensure LCDd service is started and enabled
  ansible.builtin.systemd:
    name: LCDd
    state: started
    enabled: true
