---
- name: Create the configuration directory
  file:
    path: "{{ docker_dir }}/{{ openwebui_container_name }}"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Create docker network
  ansible.builtin.include_tasks:
    file: network.yml

- name: Make sure that OpenWebUI container is created and running
  community.docker.docker_container:
    name: "{{ openwebui_container_name }}"
    image: ghcr.io/open-webui/open-webui:main
    pull: true
    networks:
      - name: "{{ openwebui_network_name }}"
    state: started
    env:
      WEBUI_SECRET_KEY: "{{ openwebui_secret_key }}"
      OPENAI_API_BASE_URL: "{{ vllm_server_url | default('https://api.openai.com') }}/v1"
    volumes:
      - "{{ docker_dir }}/{{ openwebui_container_name }}/data:/app/backend/data"
      - "{{ cache_root }}/docker-volumes-cache/{{ openwebui_container_name }}:/app/backend/data/cache"
      - /etc/localtime:/etc/localtime:ro
    restart_policy: unless-stopped
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ openwebui_dashboard_name }}"
      swag.uptime-kuma.monitor.url: "{{ openwebui_dashboard_url }}"

- name: Install the SWAG config files
  template:
    src: "{{ openwebui_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ openwebui_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"

- name: Setup backup cron job
  ansible.builtin.include_tasks: tasks/backup_service.yml
  vars:
    service_name: "{{ openwebui_container_name }}"
    cron_schedule: "0 5 * * 3"
    backup_cli_args:
      source_paths: "{{ docker_dir }}/{{ openwebui_container_name }}"
      destination_path: "{{ mergerfs_root }}/docker-volumes-backup"
      container_names_str: "{{ openwebui_container_name }}"
