system_extra_packages:
  - git
  - htop
  - iotop
  - iperf3
  - ncdu
  - neovim
  - rsync
  - sshpass
  - stow
  - sudo
  - zsh

system_sudo_group: sudo

system_enable_powersaving: "{{ enable_powersaving | default(false) }}"
